In [73]:
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn
import torch.optim as optim

In [74]:
df = pd.read_csv("fmnist_small.csv")
df.head(3)

   label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      9       0       0       0  ...       213       165         0         0
1      7       0       0       0  ...         0         0         0         0
2      0       0       0       0  ...         0         0         0         0

[3 rows x 785 columns]

In [75]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [76]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train

      pixel1  pixel2  pixel3  pixel4  ...  pixel781  pixel782  pixel783  pixel784
3897       0       0       0       0  ...         0         0         0         0
5628       0       0       0       0  ...         0         0         0         0
1756       0       0       0       0  ...         0         0         0         0
2346       0       0       0       0  ...        23         0         0         0
2996       0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
3772       0       0       0       0  ...         0         0         0         0
5191       0       0       0       0  ...         0         0         0         0
5226       0       0       0       0  ...         0         0         0         0
5390       0       0       0       0  ...         0         0         0         0
860        0       0       0       0  ...        71        16         0         0

[4800 rows x 784 columns]

In [77]:
X_train = X_train/255.0
X_test = X_test/255.0

In [47]:
  # Creating Custom Dataset Class
class CustomDataset(Dataset):
    def __init__(self, features, labels):
      self.features = torch.tensor(features, dtype=torch.float32)
      self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
      return len(self.features)

    def __getitem__(self, index):
      return self.features[index], self.labels[index]

In [48]:
# Train dataset object
train_dataset = CustomDataset(X_train.values, Y_train.values)

In [49]:
# Test Dataser object
test_dataset = CustomDataset(X_test.values, Y_test.values)

In [50]:
# Creating Train and TEst Loader
train_loader = DataLoader(train_dataset, batch_size=32, drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=32, drop_last=True)

In [79]:
# Define NN Class
class myNN(nn.Module):
    def __init__(self, input_feat):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_feat, out_features=128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.model(x)

In [66]:
learning_rate = 0.01
epoch = 100

In [67]:
model = myNN(X_train.shape[1])

In [68]:
criterion = nn.CrossEntropyLoss()

params = []
for layer in model.model:
    if isinstance(layer, nn.Module):
        params.extend(list(layer.parameters()))
optimizer = optim.SGD(params, lr=learning_rate)

In [69]:
# Training Loop
for epoch in range(epoch):
    for batch_features, batch_labels in train_loader:
        # Forward Pass
        outputs = model(batch_features)

        # Loss Calc
        loss = criterion(outputs, batch_labels)

        optimizer.zero_grad()

        # Backward Pass
        loss.backward()

        optimizer.step()

In [72]:
# Testing Model
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        outputs = model(batch_features)
        _, predicted = torch.max(outputs, 1)
        total += batch_labels.size(0)
        correct += (predicted == batch_labels).sum().item()

accuracy = 100 * correct / total
print(f'Test Accuracy: {accuracy:.2f}%')

Test Accuracy: 82.69%